-- drop old schema
DROP SCHEMA users CASCADE;
CREATE SCHEMA users AUTHORIZATION filmdb_dev;


-- 1. Auth Table
CREATE TABLE users.user_auth (
                                 user_id UUID PRIMARY KEY, -- Generated by java
                                 username VARCHAR(50) NOT NULL UNIQUE,
                                 password_hash TEXT NOT NULL,
                                 role VARCHAR(20)
);

-- 2. Profile Table
CREATE TABLE users.user_profile (
                                    user_id UUID PRIMARY KEY, -- Same ID as user_auth
                                    username VARCHAR(50) NOT NULL UNIQUE,
                                    bio TEXT,
                                    display_name VARCHAR(100),
                                    date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Dynamic Lists
CREATE TABLE users.user_list (
                                 list_id UUID PRIMARY KEY,
                                 user_id UUID NOT NULL,
                                 name_list VARCHAR(100) NOT NULL,
                                 list_type VARCHAR(20) DEFAULT 'MIXTURE',
                                 is_custom BOOLEAN,
                                 is_public BOOLEAN DEFAULT false,
                                 date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                                 CONSTRAINT unique_user_list_name UNIQUE (user_id, name_list, list_type)
);

-- 4. List Items
CREATE TABLE users.user_list_details (
                                         item_id UUID PRIMARY KEY,
                                         list_id UUID NOT NULL,
                                         movie_id VARCHAR(50) NOT NULL,
                                         state VARCHAR(20) DEFAULT 'NEUTRAL',
                                         added_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
                                         notes TEXT
);