spring:
  application:
    name: film-db
  config:
    import: optional:file:secret.env[.properties] # Treat this .env like .properties

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=search,imdb,users,admin,public
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: public,imdb,users,admin
#    default-schema: imdb
    locations: classpath:db/migration # everything in resources is moved to root
    # -on-validation-error: true # deprecated function
    clean-disabled: false

app:
  api:
    version: v1
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}ms
      refresh-expiration: ${REFRESH_TOKEN_EXPIRATION}ms
  tmdb:
    bearer-token: ${TMDB_BEARER_TOKEN:}
    image-base-url: https://image.tmdb.org/t/p/w500
  importer:
    dataset:
      location: dataset/
    scripts:
      swap-staging-tables: classpath:db2/script/swap_staging_tables.sql
      drop-staging-indexes: classpath:db2/script/drop_staging_indexes.sql
      create-staging-indexes: classpath:db2/script/create_staging_indexes.sql
      wipe-staging-tables: classpath:db2/script/wipe_staging_tables.sql



